//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Users
    {
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public string User_Location { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> RegisteredOn { get; set; }
    }
}
