//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Patients
    {
        public int Patient_ID { get; set; }
        public string Patient_Name { get; set; }
        public string Patient_Location { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> ExaminedOn { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> BMI { get; set; }
        public Nullable<double> IdealBodyWeight { get; set; }
        public Nullable<double> BodyFat { get; set; }
        public Nullable<double> BoneMass { get; set; }
        public Nullable<double> MuscleMass { get; set; }
        public Nullable<double> BodyWater { get; set; }
        public Nullable<double> Waist { get; set; }
        public Nullable<double> Hip { get; set; }
        public Nullable<double> WaistHipRatio { get; set; }
        public Nullable<double> WaistHeightRatio { get; set; }
        public string BloodPressure { get; set; }
        public Nullable<int> Pulse { get; set; }
        public Nullable<double> SPO2 { get; set; }
        public Nullable<bool> ECG { get; set; }
        public Nullable<double> HaemoglobinCount { get; set; }
        public Nullable<bool> SputumTest { get; set; }
        public Nullable<bool> VaccinationHB { get; set; }
        public Nullable<bool> VaccinationTyphoid { get; set; }
        public string EyeTest { get; set; }
        public string SkinTest { get; set; }
    }
}
