//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatient
    {
        public int PatientID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> BMI { get; set; }
        public Nullable<double> IdealBodyWeight { get; set; }
        public Nullable<double> BodyFat { get; set; }
        public Nullable<double> MuscleMass { get; set; }
        public Nullable<double> BodyMass { get; set; }
        public Nullable<double> BodyWater { get; set; }
        public Nullable<double> Waist { get; set; }
        public Nullable<double> Hip { get; set; }
        public Nullable<double> WaistHipRatio { get; set; }
        public Nullable<double> WaistHeightRatio { get; set; }
        public string BloodPressure { get; set; }
        public Nullable<double> Pulse { get; set; }
        public Nullable<double> SPO2 { get; set; }
        public Nullable<bool> ECG { get; set; }
        public Nullable<double> Hemoglobin { get; set; }
        public Nullable<bool> SputumTest { get; set; }
        public Nullable<bool> VaccinationHB { get; set; }
        public Nullable<bool> VaccinationTYPHD { get; set; }
        public Nullable<System.DateTime> ExaminedOn { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
